### ISSUE TITLE
«Call to a member function toArray() on null in vendor/mirasvit/module-dashboard/Controller/Adminhtml/Api/Request.php:74»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [dxmoto/site#98]
```
#0 vendor/magento/framework/Interception/Interceptor.php(58): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request->execute()
#1 vendor/magento/framework/Interception/Interceptor.php(138): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request\Interceptor->___callParent('execute', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(153): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request\Interceptor->Magento\Framework\Interception\{closure}()
#3 generated/code/Mirasvit/Dashboard/Controller/Adminhtml/Api/Request/Interceptor.php(39): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request\Interceptor->___callPlugins('execute', Array, Array)
#4 vendor/magento/framework/App/Action/Action.php(108): Mirasvit\Dashboard\Controller\Adminhtml\Api\Req
File: vendor/mirasvit/module-dashboard/Controller/Adminhtml/Api/Request.php
```

**Comment by dmitry-fedyuk** [comment]
I have implemented a logging in `vendor/mirasvit/module-dashboard/Controller/Adminhtml/Api/Request.php`.

**Comment by dmitry-fedyuk** [comment]
```
[
    {
        "mage2pro/core": "6.9.5",
        "Magento": "2.3.5-p1",
        "PHP": "7.2.33-1+0~20200807.47+debian10~1.gbpcb3068",
        "Referer": "https://www.dxmoto.com/panel09/dashboard/dashboard/index/",
        "URL": "https://www.dxmoto.com/panel09/dashboard/api/request",
        "Post": []
    }
]
************************************
[E_ERROR] Uncaught Error: Call to a member function toArray() on null in vendor/mirasvit/module-dashboard/Controller/Adminhtml/Api/Request.php:79
Stack trace:
#0 vendor/magento/framework/Interception/Interceptor.php(58): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request->execute()
#1 vendor/magento/framework/Interception/Interceptor.php(138): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request\Interceptor->___callParent('execute', Array)
#2 vendor/magento/framework/Interception/Interceptor.php(153): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request\Interceptor->Magento\Framework\Interception\{closure}()
#3 generated/code/Mirasvit/Dashboard/Controller/Adminhtml/Api/Request/Interceptor.php(39): Mirasvit\Dashboard\Controller\Adminhtml\Api\Request\Interceptor->___callPlugins('execute', Array, Array)
#4 vendor/magento/framework/App/Action/Action.php(108): Mirasvit\Dashboard\Controller\Adminhtml\Api\Req
File: vendor/mirasvit/module-dashboard/Controller/Adminhtml/Api/Request.php
Line: 79
```

**Comment by dmitry-fedyuk** [comment]
```
{
    "Mage2.PRO": [
        {
            "mage2pro/core": "6.9.5",
            "Magento": "2.3.5-p1",
            "PHP": "7.2.33-1+0~20200807.47+debian10~1.gbpcb3068",
            "Post": [],
            "Referer": "https://www.dxmoto.com/panel09/dashboard/dashboard/index/",
            "URL": "https://www.dxmoto.com/panel09/dashboard/api/request"
        }
    ],
    "params": {
        "block": {
            "_refresh": "",
            "config": {
                "chart": {
                    "columns": [],
                    "compare": "",
                    "dimension": ""
                },
                "date_range": {
                    "override": false,
                    "range": "life"
                },
                "filters": [],
                "renderer": "single",
                "single": {
                    "column": "sales_order|grand_total__sum",
                    "compare": "period",
                    "spark_line": true
                },
                "table": {
                    "columns": [],
                    "dimensions": [],
                    "page_size": 30,
                    "sort_orders": []
                }
            },
            "description": "",
            "identifier": "ee3f098d210ab558",
            "pos": [
                0,
                0
            ],
            "size": [
                20,
                14
            ],
            "title": "orders - grand total"
        },
        "filters": [
            {
                "column": "DATE",
                "condition_type": "gteq",
                "value": "2020-09-01 00:00:00"
            },
            {
                "column": "DATE",
                "condition_type": "lteq",
                "value": "2020-09-30 23:59:59"
            }
        ],
        "token": "b3faeec55c67ecd7"
    }
}
Location:    vendor/mirasvit/module-dashboard/Controller/Adminhtml/Api/Request.php:78
Callee:      df_log_l
*****************1******************
Location:    vendor/magento/framework/Interception/Interceptor.php:58
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::execute
*****************2******************
Location:    vendor/magento/framework/Interception/Interceptor.php:138
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::___callParent
*****************3******************
Location:    vendor/magento/framework/Interception/Interceptor.php:153
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::Magento\Framework\Interception\{closure}
*****************4******************
Location:    generated/code/Mirasvit/Dashboard/Controller/Adminhtml/Api/Request/Interceptor.php:39
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::___callPlugins
*****************5******************
Location:    vendor/magento/framework/App/Action/Action.php:108
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::execute
*****************6******************
Location:    vendor/magento/module-backend/App/AbstractAction.php:231
Callee:      Magento\Framework\App\Action\Action::dispatch
*****************7******************
Location:    vendor/mirasvit/module-dashboard/Controller/Adminhtml/Api/Request.php:59
Callee:      Magento\Backend\App\AbstractAction::dispatch
*****************8******************
Location:    vendor/magento/framework/Interception/Interceptor.php:58
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::dispatch
*****************9******************
Location:    vendor/magento/framework/Interception/Interceptor.php:138
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::___callParent
*****************10*****************
Location:    vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::Magento\Framework\Interception\{closure}
*****************11*****************
Location:    vendor/magento/framework/Interception/Interceptor.php:135
Callee:      Magento\Backend\App\Action\Plugin\Authentication::aroundDispatch
*****************12*****************
Location:    vendor/magento/framework/Interception/Interceptor.php:153
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::Magento\Framework\Interception\{closure}
*****************13*****************
Location:    generated/code/Mirasvit/Dashboard/Controller/Adminhtml/Api/Request/Interceptor.php:26
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::___callPlugins
*****************14*****************
Location:    vendor/magento/framework/App/FrontController.php:162
Callee:      Mirasvit\Dashboard\Controller\Adminhtml\Api\Request::dispatch
*****************15*****************
Location:    vendor/magento/framework/App/FrontController.php:99
Callee:      Magento\Framework\App\FrontController::processRequest
*****************16*****************
Location:    vendor/magento/framework/Interception/Interceptor.php:58
Callee:      Magento\Framework\App\FrontController::dispatch
*****************17*****************
Location:    vendor/magento/framework/Interception/Interceptor.php:138
Callee:      Magento\Framework\App\FrontController::___callParent
*****************18*****************
Location:    vendor/m2e/ebay-amazon-magento2/Plugin/HealthStatus/Magento/Framework/App/FrontController.php:81
Callee:      Magento\Framework\App\FrontController::Magento\Framework\Interception\{closure}
*****************19*****************
Location:    vendor/m2e/ebay-amazon-magento2/Plugin/AbstractPlugin.php:45
Callee:      Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController::processDispatch
*****************20*****************
Location:    vendor/m2e/ebay-amazon-magento2/Plugin/HealthStatus/Magento/Framework/App/FrontController.php:45
Callee:      Ess\M2ePro\Plugin\AbstractPlugin::execute
*****************21*****************
Location:    vendor/magento/framework/Interception/Interceptor.php:135
Callee:      Ess\M2ePro\Plugin\HealthStatus\Magento\Framework\App\FrontController::aroundDispatch
*****************22*****************
Location:    vendor/magento/framework/Interception/Interceptor.php:153
Callee:      Magento\Framework\App\FrontController::Magento\Framework\Interception\{closure}
*****************23*****************
Location:    generated/code/Magento/Framework/App/FrontController/Interceptor.php:26
Callee:      Magento\Framework\App\FrontController::___callPlugins
*****************24*****************
Location:    vendor/magento/framework/App/Http.php:116
Callee:      Magento\Framework\App\FrontController::dispatch
*****************25*****************
Location:    vendor/magento/framework/App/Bootstrap.php:261
Callee:      Magento\Framework\App\Http::launch
*****************26*****************
Location:    pub/index.php:40
Callee:      Magento\Framework\App\Bootstrap::run
```

**Comment by dmitry-fedyuk** [comment]
Particularly, it could occur when the user did not specify dimensions:
```json
[
	{
		"identifier": "86df14a17228c9b3",
		"title": "cost",
		"size": [
			5,
			10
		],
		"pos": [
			14,
			0
		],
		"description": "",
		"config": {
			"renderer": "table",
			"filters": [],
			"single": {
				"column": "",
				"spark_line": false,
				"compare": ""
			},
			"table": {
				"columns": [
					"sales_order|total_invoiced_cost__sum"
				],
				"dimensions": [],
				"sort_orders": [],
				"page_size": 30
			},
			"chart": {
				"dimension": "",
				"columns": [],
				"compare": ""
			},
			"date_range": {
				"override": false,
				"range": ""
			}
		}
	}
]
```
![02](https://user-images.githubusercontent.com/83204/94339306-dce3d300-001a-11eb-8a54-042e139f1e20.png)
